In [ ]:
import pandas as pd

In [ ]:
salary = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Salary%20Data.csv')

In [ ]:
salary.head()

   Experience Years  Salary
0               1.1   39343
1               1.2   42774
2               1.3   46205
3               1.5   37731
4               2.0   43525

In [ ]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Experience Years  40 non-null     float64
 1   Salary            40 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 768.0 bytes

In [ ]:
salary.describe()

       Experience Years         Salary
count         40.000000      40.000000
mean           5.152500   74743.625000
std            2.663715   25947.122885
min            1.100000   37731.000000
25%            3.200000   56878.250000
50%            4.600000   64472.500000
75%            6.875000   95023.250000
max           10.500000  122391.000000

In [ ]:
salary.columns

Index(['Experience Years', 'Salary'], dtype='object')

In [ ]:
y = salary['Salary']

In [ ]:
X = salary[['Experience Years']]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=2529)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((28, 1), (12, 1), (28,), (12,))

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

26596.961311068262

In [ ]:
model.coef_

array([9405.61663234])

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([ 90555.15441095,  59516.61952424, 106544.70268592,  64219.42784041,
        68922.23615658, 123474.81262412,  84911.78443155,  63278.86617718,
        65159.98950364,  61397.74285071,  37883.70126987,  50111.00289191])

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error

In [ ]:
mean_absolute_error(y_test,y_pred)

4005.9263101681768

In [ ]:
mean_absolute_percentage_error(y_test,y_pred)

0.06384602996141632

In [ ]:
mean_squared_error(y_test,y_pred)

24141421.671440993

In [ ]:
# Step 9 : save model to pickle
import pickle

# Save the model to a pickle file
with open('linear_regression_salary_model.pkl', 'wb') as file:
    pickle.dump(model, file)

print("Model saved to linear_regression_salary_model.pkl")

Model saved to linear_regression_salary_model.pkl