In [2]:
# prompt: create program to connect google colab with drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

df = pd.read_csv('/content/drive/My Drive/dataset/heart.csv')
df.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [6]:
df[(df['chol'] > 300) & (df['age'] > 50)]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
16,58,0,2,120,340,0,1,172,0,0.0,2,0,2,1
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2,1
36,54,0,2,135,304,1,1,170,0,0.0,2,0,2,1
39,65,0,2,160,360,0,0,151,0,0.8,2,0,2,1
40,51,0,2,140,308,0,0,142,0,1.5,2,1,2,1
45,52,1,1,120,325,0,1,172,0,0.2,2,0,2,1
51,66,1,0,120,302,0,0,151,0,0.4,1,0,2,1
59,57,0,0,128,303,0,0,159,0,0.0,2,1,2,1
61,54,1,1,108,309,0,1,156,0,0.0,2,0,3,1
82,60,0,2,102,318,0,1,160,0,0.0,2,1,2,1
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1
96,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1
110,64,0,0,180,325,0,1,154,1,0.0,2,0,2,1
112,64,0,2,140,313,0,1,133,0,0.2,2,0,3,1
120,64,0,0,130,303,0,1,122,0,2.0,1,2,2,1
161,55,0,1,132,342,0,1,166,0,1.2,2,0,2,1
177,64,1,2,140,335,0,1,158,0,0.0,2,0,2,0
180,55,1,0,132,353,0,1,132,1,1.2,1,1,3,0
182,61,0,0,130,330,0,0,169,0,0.0,2,0,2,0
190,51,0,0,130,305,0,1,142,1,1.2,1,0,3,0
195,59,1,0,170,326,0,0,140,1,3.4,0,0,3,0
213,61,0,0,145,307,0,0,146,1,1.0,1,0,3,0
217,63,1,0,130,330,1,0,132,1,1.8,2,3,3,0
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3,0
229,64,1,2,125,309,0,1,131,1,1.8,1,0,3,0
234,70,1,0,130,322,0,0,109,0,2.4,1,3,2,0
238,77,1,0,125,304,0,0,162,1,0.0,2,3,2,0
246,56,0,0,134,409,0,0,150,1,1.9,1,2,3,0
266,55,0,0,180,327,0,2,117,1,3.4,1,0,2,0
278,58,0,1,136,319,1,0,152,0,0.0,2,2,2,0
288,57,1,0,110,335,0,1,143,1,3.0,1,1,3,0
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0

In [7]:
X = df.iloc[:, 0:13] #independen variable
y = df.iloc[:,13] #dependen variable

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
34,51,1,3,125,213,0,0,125,1,1.4,2,1,2
185,44,1,0,112,290,0,0,153,0,0.0,2,1,2
187,54,1,0,124,266,0,0,109,1,2.2,1,1,3
147,60,0,3,150,240,0,1,171,0,0.9,2,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,68,1,2,180,274,1,0,150,1,1.6,1,0,3
255,45,1,0,142,309,0,0,147,1,0.0,1,3,3
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2
235,51,1,0,140,299,0,1,173,1,1.6,2,0,3
37,54,1,2,150,232,0,0,165,0,1.6,2,0,3

In [11]:
from sklearn import tree
from sklearn.metrics import accuracy_score
model = tree.DecisionTreeClassifier()

model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

0.7032967032967034

In [25]:
data_baru = [[57,0,0,120,354,0,1,163,1,0.6,2,0,2]]
data_baru2 = [[65,0,2,140,417,1,0,157,0,0.8,2,1,2]]
hasil = model.predict(data_baru2)[0]
print("Hasil Prediksi: " + str(hasil))

Hasil Prediksi: 1

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [13]:
import pickle

filename = '/content/drive/My Drive/dataset/model_heart.sav'
pickle.dump(model, open(filename, 'wb'))